name: zad_almumin
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  animated_button: ^0.2.0
  animated_text_kit: ^4.2.2
  audio_manager: ^0.8.2
  audioplayers: ^1.0.1
  badges: ^2.0.3
  circle_bottom_navigation_bar: ^1.0.0
  connectivity_plus: ^2.3.6+1
  convex_bottom_bar: ^3.0.0
  cupertino_icons: ^1.0.5
  curved_navigation_bar: ^1.0.3
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_inset_box_shadow: ^1.0.8
  flutter_launcher_icons: ^0.10.0
  flutter_local_notifications: ^9.7.0
  flutter_localizations:
    sdk: flutter
  flutter_native_timezone: ^2.0.0
  flutter_staggered_animations: ^1.0.0
  fluttertoast: ^8.0.9
  geolocator: ^9.0.1
  get: ^4.6.5
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  hijri: ^3.0.0
  http: ^0.13.4
  intl: ^0.17.0
  like_button: ^2.0.4
  page_transition: ^2.0.9
  path_provider: ^2.0.11
  rename: ^2.0.1
  rflutter_alert: ^2.0.4
  share_plus: ^4.0.10
  sqflite: ^2.0.3
  timezone: ^0.8.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/images/app_logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/database/azkar/
    - assets/database/hadith/
    - assets/database/quran/
    - assets/images/
    - assets/images/quran pages/
    - assets/lang/
  # fonts:
  #   - family: meQuran
  #     fonts:
  #       - asset: assets/fonts/me_quran_volt_newmet.ttf
